import javax.swing.*;
import java.io.*;
import javax.sound.sampled.*;

/*
 * To Handle the background rendering
 * the original image is Ai Generated by GPT-4o
 */
public class Background extends JPanel {
    private Clip clip;

    Background(){
        JLabel background = new JLabel(new ImageIcon("assets/background.png"));
        add(background);
        playMusic();
    }

    /*
     * Play the background music in a loop
     */
    public void playMusic(){
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File("assets/background_ost.wav"));
            clip = AudioSystem.getClip(); // Clip to run the audio
            clip.open(audio);
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY); // Loop music continuously
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error in music assets");
        }
    }

    /*
     * Stop the music when the game is over
     */
    public void pauseMusic() {
        if (clip != null) {
            if (clip.isRunning()) {
                clip.stop();  
                System.out.println("Music stopped.");
            }
        }
    }
}
